### PR TITLE
Pivot to Trails

### PR DESCRIPTION
**Pull request by matt-ramotar**
@digitalbuddha and I discussed this morning. Pivoting from Pokesocial to Trails. Cc @keith @tyvsmith 

image

### CODE REVIEW

**Comment by keith** [comment]
lmk if you want a repo rename or something (you might actually be able to do that too)

**Comment by matt-ramotar** [comment]
@keith Thanks! Yeah can you please rename to Trails?

**Comment by keith** [comment]
done

**Comment by matt-ramotar** [comment]
Thanks! 🙏🏽

**Comment by tyvsmith** [comment]
Supportive of the pivot, but curious to why? Better API?

**Comment by digitalbuddha** [comment]
Goes better with the droidcon sf talk

**Pull request merged**
